### ISSUE TITLE
Add TravisCI

### ISSUE THREAD

**Issue by dadrian** [zmap/ztag#3]
We should add Travis CI to run tests on pull-requests

**Comment by dadrian** [comment]
https://travis-ci.org/zmap/ztag

**Comment by ppannuto** [comment]
Duuuudeee... add ALL the plugins!

https://codeclimate.com/

https://coveralls.io/

I'm sure there are more...

**Comment by zakird** [comment]
This is how your website ends up looking like Pat's million dollar pixel
website instead of something with easily digestable information. :)

**Comment by dadrian** [comment]
Does coveralls even support non "import unittest" tests?

**Comment by zakird** [comment]
it sure doesn't support we rolled our own tests because we didn't like
other peoples'

**Comment by dadrian** [comment]
To be fair, we could have solved our testing problem by dynamically generating new subclasses of unittest.

**Comment by dadrian** [comment]
Code Climate rates zmap higher than ztag, which is so laughably wrong I can barely type this comment. https://codeclimate.com/github/zmap/zmap
