### ISSUE TITLE
Ztag Install Issue

### ISSUE THREAD

**Issue by rpuglisi** [zmap/ztag#33]
I am trying to install on CentOS 6.7 with Python 2.6.6  and receving the following error during python setup.py install - 
Extracting ztag-1.0.0-py2.6.egg to /usr/lib/python2.6/site-packages
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/schema.py', 808, 26, "DROP_KEYS = {'ip_address', 'metadata', 'tags', 'timestamp'}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/transforms/sslv2.py', 12, 24, '        protocols.HTTPS,\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/encoders/protobuf.py', 21, 30, "    DROP_KEYS = {'ip_address', 'timestamp', 'domain'}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/annotations/crouzet.py', 31, 24, '    tags = { "ethernet", }\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/annotations/lantronix.py', 31, 23, '    tags = {"ethernet", }\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/annotations/se_electronic.py', 43, 5, '    }\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/annotations/panasonic_web_server.py', 10, 23, '    tags = {"ethernet", }\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/annotations/schneider.py', 87, 33, '    TAGS = {Type.SCADA_PROCESSOR, }\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg/ztag/annotations/rockwell_mei.py', 25, 5, '    }\n'))

ztag 1.0.0 is already the active version in easy-install.pth
Installing ztag script to /usr/bin

Installed /usr/lib/python2.6/site-packages/ztag-1.0.0-py2.6.egg
Processing dependencies for ztag==1.0.0
Searching for zsearch-definitions
Reading http://pypi.python.org/simple/zsearch_definitions/
Download error: [Errno 1] _ssl.c:492: error:1409210A:SSL routines:SSL3_GET_SERVER_HELLO:wrong ssl version -- Some packages may not be found!
Reading http://pypi.python.org/simple/zsearch-definitions/
Download error: [Errno 1] _ssl.c:492: error:1409210A:SSL routines:SSL3_GET_SERVER_HELLO:wrong ssl version -- Some packages may not be found!
Couldn't find index page for 'zsearch_definitions' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
Download error: [Errno 1] _ssl.c:492: error:1409210A:SSL routines:SSL3_GET_SERVER_HELLO:wrong ssl version -- Some packages may not be found!
No local packages or download links found for zsearch-definitions
error: Could not find suitable distribution for Requirement.parse('zsearch-definitions')

**Comment by dadrian** [comment]
ztag requires Python 2.7

**Comment by rpuglisi** [comment]
Hi David,
Thanks for your reply. I did better installing it on my Fedora 23 server which is running Python 2.7.11 but I still received:

Installed /usr/lib/python2.7/site-packages/ztag-1.0.0-py2.7.egg
Processing dependencies for ztag==1.0.0
Searching for zsearch-definitions
Reading https://pypi.python.org/simple/zsearch_definitions/
Download error on https://pypi.python.org/simple/zsearch_definitions/: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:590) -- Some packages may not be found!
Reading https://pypi.python.org/simple/zsearch-definitions/
Download error on https://pypi.python.org/simple/zsearch-definitions/: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'zsearch_definitions' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for zsearch-definitions
error: Could not find suitable distribution for Requirement.parse('zsearch-definitions')

Any ideas? Thanks.
Richard

**Comment by dadrian** [comment]
It looks like you can't connect to Pypi because of an SSL issue. Are you system TLS libraries up to date?
