### ISSUE TITLE
MissingTransform error

### ISSUE THREAD

**Issue by chuanjiesun** [zmap/ztag#46]
When I "ztag -p 102 -P s7 -S banner  -i banner.json",
it return an error :
 "File "/usr/local/bin/ztag", line 11, in <module>
    load_entry_point('ztag==1.0.0', 'console_scripts', 'ztag')()
  File "/usr/local/lib/python2.7/dist-packages/ztag-1.0.0-py2.7.egg/ztag/__main__.py", line 112, in main
    scan_id)
  File "/usr/local/lib/python2.7/dist-packages/ztag-1.0.0-py2.7.egg/ztag/transformer.py", line 26, in find_transform
    raise errors.MissingTransform
ztag.errors.MissingTransform",

I run this on Linux kali 4.8.0-kali1-amd64 ,
how ho solve this error?

**Comment by dadrian** [comment]
The only transform we have for S7 is for the subprotocol `szl`. See https://github.com/zmap/ztag/blob/86ef36d7afd366da5e2ff2cb6ac4c136d13ff5f4/ztag/transforms/s7.py.

Try running `ztag -p 102 -P s7 -S szl -i banner.json`. If ztag yells at you about needing a scan id, add `-s 1`.

**Comment by chuanjiesun** [comment]
Is there any user mannual about verbose useage yhe protocol and subprotocol>

**Comment by dadrian** [comment]
Unfortunately, no. Your best bet is to grep through the `transforms` folder.
