### ISSUE TITLE
Cannot install under OSX

### ISSUE THREAD

**Issue by kuekerino** [zmap/ztag#52]
When installing ztag under OSX I get the following error: 

`Installed /usr/local/lib/python2.7/site-packages/ztag-1.0.0-py2.7.egg
Processing dependencies for ztag==1.0.0
error: protobuf 3.0.0 is installed but protobuf>=3.2.0 is required by set(['grpcio']) `

I have protobuf3.2.0 in my site packages folder but somehow the install process always creates the 3.0.0 folder on which it then relies

**Comment by dadrian** [comment]
We accidentally created a set of impossible to satisfy dependencies earlier this week. We're working on sorting it out.

**Comment by dadrian** [comment]
This should be resolved.
